config/routes.rb
Rails.application.routes.draw do

  resources :situations
  resources :militaries
  resources :people
  resources :addresses
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :opms, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :user_permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :situations

  # Rotas para aplicações React.js
  # Essa rota funciona como um entry point para a aplicação frontend
  get 'chamadas', to: 'chamadas#index'

end

app/models/military.rb
class Military < ApplicationRecord
  belongs_to :user

  has_many :situations
end

app/controllers/militaries_controller.rb
class MilitariesController < BaseController
  before_action :set_military, only: [:show, :edit, :update, :destroy]

  # GET /militaries
  # GET /militaries.json
  def index
    @militaries = Military.all
  end

  # GET /militaries/1
  # GET /militaries/1.json
  def show
  end

  # GET /militaries/new
  def new
    @military = Military.new
  end

  # GET /militaries/1/edit
  def edit
  end

  # POST /militaries
  # POST /militaries.json
  def create
    @military = Military.new(military_params)

    respond_to do |format|
      if @military.save
        format.html { redirect_to @military, notice: 'Military was successfully created.' }
        format.json { render :show, status: :created, location: @military }
      else
        format.html { render :new }
        format.json { render json: @military.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /militaries/1
  # PATCH/PUT /militaries/1.json
  def update
    respond_to do |format|
      if @military.update(military_params)
        format.html { redirect_to @military, notice: 'Military was successfully updated.' }
        format.json { render :show, status: :ok, location: @military }
      else
        format.html { render :edit }
        format.json { render json: @military.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /militaries/1
  # DELETE /militaries/1.json
  def destroy
    @military.destroy
    respond_to do |format|
      format.html { redirect_to militaries_url, notice: 'Military was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_military
      @military = Military.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def military_params
      params.require(:military).permit(:name, :rank, :registration, :admission_date, :t_shirt_size, :boot_size, :beret_size, :pants_size, :user_id)
    end
end

app/helpers/militaries_helper.rb
module MilitariesHelper
end

app/views/militaries/_fields.html.erb
<div class="form-group">
  <%= m.label :name %>
  <%= m.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= m.label :admission_date %>
  <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
    <div class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </div>
    <%= m.text_field :admission_date, class: 'form-control pull-right' %>
</div>
</div>

<div class="form-group">
  <%= m.label :rank %>
  <%= m.text_field :rank, class: 'form-control' %>
</div>

<div class="form-group">
  <%= m.label :registration %>
  <%= m.text_field :registration, class: 'form-control' %>
</div>


<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/militaries/_form.html.erb
<%= form_for(military) do |f| %>
  <% if military.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(military.errors.count, "error") %> prohibited this military from being saved:</h2>

      <ul>
      <% military.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rank %>
    <%= f.number_field :rank %>
  </div>

  <div class="field">
    <%= f.label :registration %>
    <%= f.text_field :registration %>
  </div>

  <div class="field">
    <%= f.label :admission_date %>
    <%= f.date_select :admission_date %>
  </div>

  <div class="field">
    <%= f.label :t_shirt_size %>
    <%= f.number_field :t_shirt_size %>
  </div>

  <div class="field">
    <%= f.label :boot_size %>
    <%= f.number_field :boot_size %>
  </div>

  <div class="field">
    <%= f.label :beret_size %>
    <%= f.number_field :beret_size %>
  </div>

  <div class="field">
    <%= f.label :pants_size %>
    <%= f.number_field :pants_size %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/militaries/edit.html.erb
<h1>Editing Military</h1>

<%= render 'form', military: @military %>

<%= link_to 'Show', @military %> |
<%= link_to 'Back', militaries_path %>

app/views/militaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Militaries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rank</th>
      <th>Registration</th>
      <th>Admission date</th>
      <th>T shirt size</th>
      <th>Boot size</th>
      <th>Beret size</th>
      <th>Pants size</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @militaries.each do |military| %>
      <tr>
        <td><%= military.name %></td>
        <td><%= military.rank %></td>
        <td><%= military.registration %></td>
        <td><%= military.admission_date %></td>
        <td><%= military.t_shirt_size %></td>
        <td><%= military.boot_size %></td>
        <td><%= military.beret_size %></td>
        <td><%= military.pants_size %></td>
        <td><%= military.user %></td>
        <td><%= link_to 'Show', military %></td>
        <td><%= link_to 'Edit', edit_military_path(military) %></td>
        <td><%= link_to 'Destroy', military, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Military', new_military_path %>

app/views/militaries/new.html.erb
<h1>New Military</h1>

<%= render 'form', military: @military %>

<%= link_to 'Back', militaries_path %>

app/views/militaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @military.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @military.rank %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @military.registration %>
</p>

<p>
  <strong>Admission date:</strong>
  <%= @military.admission_date %>
</p>

<p>
  <strong>T shirt size:</strong>
  <%= @military.t_shirt_size %>
</p>

<p>
  <strong>Boot size:</strong>
  <%= @military.boot_size %>
</p>

<p>
  <strong>Beret size:</strong>
  <%= @military.beret_size %>
</p>

<p>
  <strong>Pants size:</strong>
  <%= @military.pants_size %>
</p>

<p>
  <strong>User:</strong>
  <%= @military.user %>
</p>

<%= link_to 'Edit', edit_military_path(@military) %> |
<%= link_to 'Back', militaries_path %>