config/routes.rb
Rails.application.routes.draw do

  resources :situations
  resources :militaries
  resources :people
  resources :addresses
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :opms, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :user_permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :situations

  # Rotas para aplicações React.js
  # Essa rota funciona como um entry point para a aplicação frontend
  get 'chamadas', to: 'chamadas#index'

end

app/models/situation.rb
class Situation < ApplicationRecord
  belongs_to :military
end

app/controllers/situations_controller.rb
class SituationsController < BaseController
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  # GET /situations
  # GET /situations.json
  def index
    @situations = Situation.all
  end

  # GET /situations/1
  # GET /situations/1.json
  def show
  end

  # GET /situations/new
  def new
    @situation = Situation.new
  end

  # GET /situations/1/edit
  def edit
  end

  # POST /situations
  # POST /situations.json
  def create
    @situation = Situation.new(situation_params)

    respond_to do |format|
      if @situation.save
        format.html { redirect_to @situation, notice: 'Situation was successfully created.' }
        format.json { render :show, status: :created, location: @situation }
      else
        format.html { render :new }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /situations/1
  # PATCH/PUT /situations/1.json
  def update
    respond_to do |format|
      if @situation.update(situation_params)
        format.html { redirect_to @situation, notice: 'Situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @situation }
      else
        format.html { render :edit }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /situations/1
  # DELETE /situations/1.json
  def destroy
    @situation.destroy
    respond_to do |format|
      format.html { redirect_to situations_url, notice: 'Situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situation
      @situation = Situation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def situation_params
      params.require(:situation).permit(:status, :functional, :medical, :juridical, :special, :alienation, :disciplinary, :gun_license, :military_id)
    end
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/views/situations/_fields.html.erb
<%= render 'shared/errors', object: f.object %>

<div class="form-group">
  <%= f.label :status %>
  <%= f.text_field :status, class: 'form-control', placeholder: 'Regime'  %>
</div>
<div class="form-group">
  <%= f.label :functional %>
  <%= f.text_field :functional, class: 'form-control', placeholder: 'Situação Funcional'  %>
</div>
<div class="form-group">
  <%= f.label :medical %>
  <%= f.text_field :medical, class: 'form-control', placeholder: 'Situação Médica'  %>
</div>
<div class="form-group">
  <%= f.label :juridical %>
  <%= f.text_field :juridical, class: 'form-control', placeholder: 'Situação Jurídica'  %>
</div>
<div class="form-group">
  <%= f.label :special %>
  <%= f.text_field :special, class: 'form-control', placeholder: 'Situação Especial'  %>
</div>
<div class="form-group">
  <%= f.label :alienation %>
  <%= f.text_field :alienation, class: 'form-control', placeholder: 'Afastamento'  %>
</div>
<div class="form-group">
  <%= f.label :disciplinary %>
  <%= f.text_field :disciplinary, class: 'form-control', placeholder: 'Situação Disciplinar'  %>
</div>
<div class="field">
  <%= f.hidden_field :user_id %>
</div>

app/views/situations/_form.html.erb
<%= form_for(situation) do |f| %>
  <% if situation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(situation.errors.count, "error") %> prohibited this situation from being saved:</h2>

      <ul>
      <% situation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :functional %>
    <%= f.text_field :functional %>
  </div>

  <div class="field">
    <%= f.label :medical %>
    <%= f.text_field :medical %>
  </div>

  <div class="field">
    <%= f.label :juridical %>
    <%= f.text_field :juridical %>
  </div>

  <div class="field">
    <%= f.label :special %>
    <%= f.text_field :special %>
  </div>

  <div class="field">
    <%= f.label :alienation %>
    <%= f.text_field :alienation %>
  </div>

  <div class="field">
    <%= f.label :disciplinary %>
    <%= f.text_field :disciplinary %>
  </div>

  <div class="field">
    <%= f.label :gun_license %>
    <%= f.text_field :gun_license %>
  </div>

  <div class="field">
    <%= f.label :military_id %>
    <%= f.text_field :military_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/situations/edit.html.erb
<h1>Editing Situation</h1>

<%= render 'form', situation: @situation %>

<%= link_to 'Show', @situation %> |
<%= link_to 'Back', situations_path %>

app/views/situations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Situations</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Functional</th>
      <th>Medical</th>
      <th>Juridical</th>
      <th>Special</th>
      <th>Alienation</th>
      <th>Disciplinary</th>
      <th>Gun license</th>
      <th>Military</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @situations.each do |situation| %>
      <tr>
        <td><%= situation.status %></td>
        <td><%= situation.functional %></td>
        <td><%= situation.medical %></td>
        <td><%= situation.juridical %></td>
        <td><%= situation.special %></td>
        <td><%= situation.alienation %></td>
        <td><%= situation.disciplinary %></td>
        <td><%= situation.gun_license %></td>
        <td><%= situation.military %></td>
        <td><%= link_to 'Show', situation %></td>
        <td><%= link_to 'Edit', edit_situation_path(situation) %></td>
        <td><%= link_to 'Destroy', situation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Situation', new_situation_path %>

app/views/situations/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3>Nova Situação</h3>

        <%= form_for(@situation) do |f| %>
        <%= render 'fields', f: f %>
        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
        <% end %>
      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>

app/views/situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @situation.status %>
</p>

<p>
  <strong>Functional:</strong>
  <%= @situation.functional %>
</p>

<p>
  <strong>Medical:</strong>
  <%= @situation.medical %>
</p>

<p>
  <strong>Juridical:</strong>
  <%= @situation.juridical %>
</p>

<p>
  <strong>Special:</strong>
  <%= @situation.special %>
</p>

<p>
  <strong>Alienation:</strong>
  <%= @situation.alienation %>
</p>

<p>
  <strong>Disciplinary:</strong>
  <%= @situation.disciplinary %>
</p>

<p>
  <strong>Gun license:</strong>
  <%= @situation.gun_license %>
</p>

<p>
  <strong>Military:</strong>
  <%= @situation.military %>
</p>

<%= link_to 'Edit', edit_situation_path(@situation) %> |
<%= link_to 'Back', situations_path %>