config/routes.rb
Rails.application.routes.draw do

  resources :situations
  resources :militaries
  resources :people
  resources :addresses
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :opms, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :user_permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :situations

  # Rotas para aplicações React.js
  # Essa rota funciona como um entry point para a aplicação frontend
  get 'chamadas', to: 'chamadas#index'

end

app/models/person.rb
class Person < ApplicationRecord
  # attr_accessor :full_name, :birth_date, :cpf, :home_phone, :home_phone, :rg
  belongs_to :address
  accepts_nested_attributes_for :address

  has_one :user

  scope :filter_by_full_name, lambda { |keyword| where("lower(full_name) LIKE ?", "%#{keyword.downcase}%") }
  scope :filter_by_cpf, lambda { |keyword| where("lower(cpf) LIKE ?", "%#{keyword.downcase}%") }
end

app/controllers/people_controller.rb
class PeopleController < BaseController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:full_name, :birth_date, :cpf, :home_phone, :mobile_phone, :rg, :address_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_fields.html.erb
<div class="form-group">
  <%= p.label :full_name %>
  <%= p.text_field :full_name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= p.label :birth_date %>
  <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
    <div class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </div>
    <%= p.text_field :birth_date, class: 'form-control pull-right' %>
</div>
</div>

<div class="form-group">
  <%= p.label :cpf %>
  <%= p.text_field :cpf, class: 'form-control' %>
</div>

<div class="form-group">
  <%= p.label :home_phone %>
  <%= p.text_field :home_phone, class: 'form-control' %>
</div>

<div class="form-group">
  <%= p.label :mobile_phone %>
  <%= p.text_field :mobile_phone, class: 'form-control' %>
</div>

<div class="form-group">
  <%= p.label :rg %>
  <%= p.text_field :rg, class: 'form-control' %>
</div>

<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :birth_date %>
    <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
      <div class="input-group-addon">
        <i class="fa fa-calendar"></i>
      </div>
      <%= f.text_field :birth_date, class: 'form-control pull-right' %>
  </div>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :home_phone %>
    <%= f.text_field :home_phone %>
  </div>

  <div class="field">
    <%= f.label :mobile_phone %>
    <%= f.text_field :mobile_phone %>
  </div>

  <div class="field">
    <%= f.label :rg %>
    <%= f.text_field :rg %>
  </div>

  <div class="field">
    <%= f.label :address_id %>
    <%= f.text_field :address_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Birth date</th>
      <th>Cpf</th>
      <th>Home phone</th>
      <th>Mobile phone</th>
      <th>Rg</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.full_name %></td>
        <td><%= person.birth_date %></td>
        <td><%= person.cpf %></td>
        <td><%= person.home_phone %></td>
        <td><%= person.mobile_phone %></td>
        <td><%= person.rg %></td>
        <td><%= person.address %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @person.full_name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @person.birth_date %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @person.cpf %>
</p>

<p>
  <strong>Home phone:</strong>
  <%= @person.home_phone %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @person.mobile_phone %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @person.rg %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.address %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>