config/routes.rb
Rails.application.routes.draw do

  resources :situations
  resources :militaries
  resources :people
  resources :addresses
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :opms, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :user_permissions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :situations

  # Rotas para aplicações React.js
  # Essa rota funciona como um entry point para a aplicação frontend
  get 'chamadas', to: 'chamadas#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :military
  has_one :situation

  has_many :placements
  has_many :opms, through: :placements
  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :user_permissions
  has_many :permissions, through: :user_permissions
  has_many :user_sessions

  belongs_to :opm
  belongs_to :person

  accepts_nested_attributes_for :person
  accepts_nested_attributes_for :military

  # validates :first_name, :last_name, :email, presence: true

  before_save :get_roles_from_permissions

  # Dynamic check for user role using the method pattern: has_role_*?
  def method_missing(method_name, *args)
    super if !method_name.to_s.match(/^has_role_(.*)\?$/)
    role_name = method_name.to_s.gsub(/(^has_role_|\?$)/, '')
    has_role?(role_name)
  end

  def update_current_placement
    if !self.opm.nil?
      current_placement = self.placements.last
      current_placement.end_date = Date.now unless current_placement.nil?
      Placement.create(user: self, opm: self.opm, start_date: Date.now)
    end
  end

  def full_name
    "#{self.first_name.capitalize} #{self.last_name.capitalize}"
  end

  scope :filter_by_email, lambda { |keyword| where("lower(email) LIKE ?", "%#{keyword.downcase}%") }
  scope :filter_by_full_name, lambda { |keyword| joins(:person).where("lower(people.full_name) LIKE ?", "%#{keyword.downcase}%") }
  scope :filter_by_cpf, lambda { |keyword| joins(:person).where("people.cpf LIKE ?", "%#{keyword.downcase}%") }
  scope :filter_by_registration, lambda { |keyword| joins(:military).where("militaries.registration LIKE ?", "%#{keyword.downcase}%") }

  # scope :filter_by_first_name, lambda { |keyword| where("lower(first_name) LIKE ?", "%#{keyword.downcase}%") }
  # scope :filter_by_last_name, lambda { |keyword| where("lower(last_name) LIKE ?", "%#{keyword.downcase}%") }
  scope :filter_by_opm_ids, lambda { |opm_ids| where("opm_id IN (?)", opm_ids) }

  def self.search(params = {})
    users = User.all
    if params[:opms_id].present?
      users = User.filter_by_opm_ids(params[:opm_ids])
    elsif params[:opms_id].present? && params[:opms_id].empty?
      users = User.none
    end
    users = users.filter_by_full_name(params[:full_name]) if params[:full_name].present?
    users = users.filter_by_cpf(params[:cpf]) if params[:cpf].present?
    users = users.filter_by_email(params[:email]) if params[:email].present?
    users = users.filter_by_registration(params[:registration]) if params[:registration].present?
    # users = users.filter_by_last_name(params[:last_name]) if params[:last_name].present?
    # users = users.filter_by_opm_ids(params[:opm_ids]) if params[:opm_ids].present?
    users
  end

  # Find user by token
  def self.find_by_token(token)
    token = UserSession.find_by(token: token)
    if !token.nil? && token.expire_date > Time.now
      token.user
    else
      nil
    end
  end

  def has_role?(role_name)
    !self.roles.where(name: role_name).empty?
  end

  def has_permission?(permission_name)
    !self.permissions.where(name: permission_name).empty?
  end

  protected
    def get_roles_from_permissions
      self.roles = self.permissions.map { |p| p.roles }.flat_map { |role| role }
    end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  layout 'users/application'

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  layout 'users/application'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < BaseController

  before_action :load_permissions, only: [:new, :edit, :create, :update]
  before_action :user_or_not_found, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
    @user.build_person
    @user.build_military
    @user.person.build_address
  end

  def index
    busca = params[:search].present? ? params[:search] : {}
    @users = User.search(busca).page(params[:page]).per(20)
    respond_to do |format|
      format.js { render json: @users, status: 200 }
      format.html
    end
  end

  def show
  end

  def edit
  end

  def create
  #
  # #   permissions = [
  # #   { permission_id: 1, category: 'category' },
  # #   { permission_id: 2, category: 'funcional' }
  # # ]
  #
  # permissions.each do |p|
  #   permission = UserPermission.new(permission_id: p[:permission_id], user_id: @user.id, category: p[:category])
  # end

    @user = User.new(user_params)
    generate_default_password
    permission_ids = params[:permission_ids]
    category = params[:category] ? params[:category] : 'funcional'
    if @user.save
      # permission_ids.each do |p|
      #   user_permission = UserPermission.new(permission_id: p, user_id: @user.id, category: category)
      #   user_permission.save
      # end
      flash[:success] = "Usuario cadastrado"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash['success'] = 'Usuario atualizado'
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def update_permission
    respond_to do |format|
      if @user.update(user_params)
        format.json{
          render json: @user,
          status: :updated,
          location: @user
        }
      else
        format.json{
          render json: @users.errors,
          status: :unprocessable_entity
        }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  protected

    def load_permissions
      @permissions = generate_permissions
      @permissions.each do |i|
          puts  'ola '
          puts i
      end
    end

    def generate_default_password
      @user.password = '12345678'
      @user.password_confirmation = '12345678'
    end

    def user_or_not_found
      @user = User.find_by(id: params[:id])
      if @user.nil?
        flash['danger'] = 'Usuario não encontrado.'
        redirect_to users_path
      end

    end

    def user_params
      user_params = params.require(:user).permit(
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :opm_id,
                                   permission_ids: [],
                                   military_attributes: [
                                   :name,
                                   :rank,
                                   :registration,
                                   :admission_date],
                                   person_attributes: [
                                   :full_name,
                                   :mobile_phone,
                                   :home_phone,
                                   :birth_date,
                                   :rg,
                                   :cpf,
                                   address_attributes: [
                                   :street,
                                   :number,
                                   :district,
                                   :zip,
                                   :city,
                                   :state]])
      user_params[:permission_ids] = user_params[:permission_ids].concat(params[:permission_ids])
      user_params
    end

end

app/views/users/_fields.html.erb
<%= render 'shared/errors', object: f.object %>


<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
</div>

<div class="form-group">
  <%= f.label :opm_id, "OPM de Trabalho" %>
  <%= f.select :opm_id, Opm.all.collect {|opm| [opm.name.titleize, opm.id]}, {include_blank: 'Selecione uma OPM'}, { class: 'form-control' } %>
</div>

<%= f.hidden_field 'permission_ids[]', value: [] %>
<%= hidden_field_tag 'permission_ids[]'%>

<div class="form-group">
  <%= f.label "Papeis"%>
  <ul>
  <% Permission.all.each do |permission| %>

    <li>
      <div class="checkbox">
        <label>
          <%= check_box_tag "permission_ids[]", permission.id, user.permissions.include?(permission), id: "user_#{permission.name}"%>
          <%= f.label permission.human_name %>
        </label>
      </div>
    </li>

  <% end %>
  </ul>
</div>
<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/users/_fields_permissions.html.erb
<%= f.hidden_field 'permission_ids[]', value: [] %>
<%= hidden_field_tag 'permission_ids[]'%>

<div class="form-group">
  <%= f.label "Papeis"%>
  <ul>
    <% Permission.all.each do |permission| %>
      <li class="list-group-item">
        <div class="row">
          <div class="col-md-3 checkbox">
            <label>
              <%= check_box_tag "permission_ids[]", permission.id, user.permissions.include?(permission), id: "user_#{permission.name}"%>
              <%= f.label permission.human_name %>
            </label>
          </div>
          <div class="col-md-9">
            <%= select_tag(:category, options_for_select([['Adicional', 'adicional'],['Funcional', 'funcional'], ['Genérico', 'generico']]), { class: 'form-control' }) %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<script>
    $('.input-group.date').datepicker({
    	format: 'dd/mm/yyyy',
    	language: 'pt-BR',
    	todayHighlight: true
    });
</script>

app/views/users/_left_side.html.erb
<!-- Left side column app. contains the tools -->
<ul class="sidebar-menu">
  <li class="header">FUNCIONALIDADES</li>
  <li>
    <%= link_to users_path, :class => "aside-padding-left" do %>
        <i class="icon-side-left fa fa-home bg-green" style="width: 35px;"></i>
        <span>
          <ul class="control-sidebar-menu">
            <li>
              <div class="menu-info">
                  <h4 class="control-sidebar-subheading">Início</h4>
                  <p>Recursos Humanos</p>
              </div>
            </li>
          </ul>
        </span>
    <% end %>
  </li>
  <li>
    <%= link_to users_path, :class => "aside-padding-left" do %>
        <i class="icon-side-left fa fa-list bg-blue" style="width: 35px;"></i>
        <span>
          <ul class="control-sidebar-menu">
            <li>
              <div class="menu-info">
                  <h4 class="control-sidebar-subheading">Consultar</h4>
                  <p>Consultar usuários</p>
              </div>
            </li>
          </ul>
        </span>
    <% end %>
  </li>
  <li>
    <%= link_to new_user_path, :class => "aside-padding-left" do %>
      <i class="icon-side-left fa fa-plus bg-yellow" style="width: 35px;"></i>
      <span>
        <ul class="control-sidebar-menu">
          <li>
            <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cadastrar</h4>
                <p>Cadastrar novo usuário</p>
            </div>
          </li>
        </ul>
      </span>
    <% end %>
  </li>
  <li class="header">SISTEMA</li>
  <li>
    <%= link_to destroy_user_session_path, method: :delete, :class => "aside-padding-left" do %>
      <i class="icon-side-left fa fa-sign-out bg-black" style="width: 35px;"></i>
      <span>
        <ul class="control-sidebar-menu">
          <li>
            <div class="menu-info">
                <h4 class="control-sidebar-subheading">Sair</h4>
                <p>Desconectar do Sistema</p>
            </div>
          </li>
        </ul>
      </span>
    <% end %>
  </li>

app/views/users/consult.html.erb
<% provide(:current_page, "Recursos Humanos") %>  <!--Titulo no content header-->
<% provide(:current_page_version, "Consulta de Servidor") %> <!--Versão do aplicativo-->

<% content_for :left_side do %>
  <%= render 'left_side' %>
<% end %>

  <div class="row">
    <div class="col-xs-12">



      <div class="box box-primary">
        <!-- form start -->
        <%= form_for :search, url: users_path, method: :get, html: {role: 'form'} do |f|%>
          <div class="box-body">

              <div class="form-group col-lg-4">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'busque pelo nome' %>
              </div>

            <div class="form-group col-lg-4">
              <br />
              <%= f.submit :buscar, class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="width: 10px">#</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Permissões</th>
              <th colspan="3">Ações</th>
            </tr>
          </thead>
          <tbody>
            <% if @users.empty? %>
            <tr>
              <td colspan="5" style="text-align: center"><h3>Nem um usuário encontrado.</h3></td>
            </tr>
            <% end %>
          <% @users.each_with_index do |user, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td class="col-xs-4"><%= "#{user.person.full_name}" %></td>
            <td class="col-xs-2"><%= user.email %></td>
            <td class="col-xs-1">
              <% user.permissions.each do |permission| %>
                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="<%= permission.description %>"><%= permission.human_name %></span>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to user_path(user) do %>
                <i class="fa fa-2x fa-eye"></i>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to edit_user_path(user) do %>
                <i class="fa fa-2x fa-edit"></i>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to user_path(user), method: :delete, data: {confirm: "Voce tem certeza?"} do %>
                <i class="fa fa-2x fa-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>
        <div class="box-footer clearfix">
            <%= paginate @users %>
        </div>

      </div>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:current_page, "Recursos Humanos") %>
<% provide(:current_page_version, "Editar Usuário") %>

<% content_for :left_side do %>
  <%= render 'left_side' %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Editar Usuario</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->

      <%= form_for @user, html: { role: 'form'} do |f| %>
        <div class="box-body">

          <%= render 'fields', f: f, user: @user %>

          <h3>Dados Pessoais</h3>
          <%= f.fields_for :person do |p| %>
          <%= render 'people/fields', p: p %>
          <%= p.fields_for :address do |a| %>
          <%= render 'addresses/fields', a: a %>
          <% end %>
        <% end %>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Atualizar</button>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.box -->

  </div>
</div>

app/views/users/index.html.erb
<% provide(:current_page, "Recursos Humanos") %>
<% provide(:current_page_version, "v1.0") %> <!--Versão do aplicativo-->

<% content_for :left_side do %>
  <%= render 'left_side' %>
<% end %>

  <div class="row">
    <div class="col-xs-12">



      <div class="box box-primary">
        <!-- form start -->
        <%= form_for :search, url: users_path, method: :get, html: {role: 'form'} do |f|%>
          <div class="box-body">

              <div class="form-group col-lg-3">
                <%= f.label "Nome" %>
                <%= f.text_field :full_name, class: 'form-control', placeholder: 'busque pelo nome' %>
              </div>

              <div class="form-group col-lg-2">
                <%= f.label :cpf %>
                <%= f.text_field :cpf, class: 'form-control', placeholder: 'busque pelo CPF' %>
              </div>

              <div class="form-group col-lg-3">
                <%= f.label "E-mail" %>
                <%= f.text_field :email, class: 'form-control', placeholder: 'busque pelo e-mail' %>
              </div>
              <div class="form-group col-lg-3">
                <%= f.label "Matrícula" %>
                <%= f.text_field :registration, class: 'form-control', placeholder: 'busque pela matrícula' %>
              </div>

            <div class="form-group col-lg-2">
              <br />
              <%= f.submit :buscar, class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="width: 10px">#</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Permissões</th>
              <th colspan="3">Ações</th>
            </tr>
          </thead>
          <tbody>
            <% if @users.empty? %>
            <tr>
              <td colspan="5" style="text-align: center"><h3>Nem um usuário encontrado.</h3></td>
            </tr>
            <% end %>
          <% @users.each_with_index do |user, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td class="col-xs-4"><%= "#{user.person.full_name}" %></td>
            <td class="col-xs-2"><%= user.email %></td>
            <td class="col-xs-1">
              <% user.permissions.each do |permission| %>
                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="<%= permission.description %>"><%= permission.human_name %></span>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to user_path(user) do %>
                <i class="fa fa-2x fa-eye"></i>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to edit_user_path(user) do %>
                <i class="fa fa-2x fa-edit"></i>
              <% end %>
            </td>
            <td class="col-xs-1">
              <%= link_to user_path(user), method: :delete, data: {confirm: "Voce tem certeza?"} do %>
                <i class="fa fa-2x fa-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>
        <div class="box-footer clearfix">
            <%= paginate @users %>
        </div>

      </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:current_page, "Recursos Humanos") %>
<% provide(:current_page_version, "Cadastrar Usuário") %>

<% content_for :left_side do %>
  <%= render 'left_side' %>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Formulario de Cadastro</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->

      <%= form_for @user, html: { role: 'form'} do |f| %>
        <div class="box-body">

          <%= render 'fields', f: f, user: @user %>
          <h3>Dados Profissionais</h3>
          <%= f.fields_for :military do |m| %>
            <%= render 'militaries/fields', m: m %>
          <% end %>
          <h3>Dados Pessoais</h3>
          <%= f.fields_for :person do |p| %>
            <%= render 'people/fields', p: p %>
            <%= p.fields_for :address do |a| %>
              <%= render 'addresses/fields', a: a %>
            <% end %>
          <% end %>

          <div class="box-footer">
            <button type="submit" class="btn btn-primary btn-block">Salvar</button>
          </div>
        </div>
      <% end %>
    </div>
    <!-- /.box -->

  </div>
</div>

app/views/users/show.html.erb
<% provide(:current_page, 'Usuário') %>

<div class="row">
  <div class="col-md-12">

    <div class="box box-primary">
      <div class="box-body box-profile">
        <%= image_tag 'militar.png', class: 'profile-user-img img-responsive img-circle' %>

        <h3 class="profile-username text-center"><%= @user.military.name %></h3>

        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>Nome completo</b> <span class="pull-right"><%= @user.person.full_name %></span>
          </li>
          <li class="list-group-item">
            <b>CPF</b> <span class="pull-right"><%= @user.person.cpf %></span>
          </li>
          <li class="list-group-item">
            <b>RG</b> <span class="pull-right"><%= @user.person.rg %></span>
          </li>
          <li class="list-group-item">
            <b>Celular</b> <span class="pull-right"><%= @user.person.mobile_phone %></span>
          </li>
          <li class="list-group-item">
            <b>Telefone</b> <span class="pull-right"><%= @user.person.home_phone %></span>
          </li>
          <li class="list-group-item">
            <b>Email</b> <span class="pull-right"><%= @user.email %></span>
          </li>
        </ul>
      </div>
      <!-- /.box-body -->
    </div>

    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3>Dados Profissionais</h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>Matrícula</b> <span class="pull-right"><%= @user.military.registration %></span>
          </li>
          <li class="list-group-item">
            <b>Patente</b> <span class="pull-right"><%= @user.military.rank %></span>
          </li>
          <li class="list-group-item">
            <b>Data de Admissão</b> <span class="pull-right"><%= @user.military.admission_date.strftime("%d/%m/%Y") if @user.military.admission_date.present? %></span>
          </li>
        </ul>
      </div>
      <!-- /.box-body -->
    </div>

    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3>Endereço</h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>Logradouro</b> <span class="pull-right"><%= "#{@user.person.address.street}, Nº #{@user.person.address.number} " %></span>
          </li>
          <li class="list-group-item">
            <b>Bairro</b> <span class="pull-right"><%= @user.person.address.district %></span>
          </li>
          <li class="list-group-item">
            <b>Cidade</b> <span class="pull-right"><%= @user.person.address.city %></span>
          </li>
        </ul>
      </div>
      <!-- /.box-body -->
    </div>

    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3>Situações</h3>
        <!--  @user.situation do |f_situation| -->
        <!-- render '../situations/fields', f: f_situation -->
        <!-- end  -->
      </div>
      <!-- /.box-body -->
    </div>

  </div>
</div>